---
title: "main_project"
author: "Yulia"
date: '2 декабря 2021 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,     # отображение кода в итоговом документе
                      message = FALSE,  # отображение сообщений в итоговом документе
                      error = FALSE,    # отображение ошибок в итоговом документе
                      warning = FALSE,  # отображение предупреждений в итоговом документе
                      cache = FALSE,    # надо ли сохранять код в чанках до их изменений
                      fig.height = 10, # высота рисунка в дюймах
                      fig.width = 10)  # широта рисунка в дюймах


library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
```

## R Markdown
Читаем файл

```{r }
df_raw <- read_excel("./data/raw/reconstitution_v1_enc.xlsx")
str(df_raw)
View(df_raw)
```

## All data modifications

```{r pressure, echo=FALSE}

df <- df_raw  %>%
  # переименование
  rename(Restage_on_TKM_point = "Рестадирование на момент ТКМ (стадия)[ПредТКМэ]" ) %>%
  rename(Age = "Возраст (полных лет) на момент ТКМ") %>% 
  rename(BMI = "Индекс массы тела") %>%
  rename(Conditioning = "Режим кондиционирования[ПредТКМэ]") %>%
  rename(BMT_kind = "Вид ТКМ настоящей [ПТКМ,ПредТКМэ,ПДИТКМ]") %>%
  rename(Source_sc = "Источник[ПредТКМэ,ПТКМ,ПДИ]") %>%
  rename(Donor_sex = "Donor sex") %>%
  rename(Sex = "Пол") %>%
  rename(Disease_state_reconstitution = "State of the disease_reconstitution") %>%
  rename(Reconstitution = "reconstitution") %>%
  rename(HLA_match = "HLA-match") %>%
  rename(Transplantation_date = "Дата ТКМ (из протокола)[ПТКМ,ПДИ]") %>%
  rename(Diagnosis_date = "Дата диагноза [АЗ гем]") %>%
  rename(Leukocyte_recovery = "Восстановление Лейкоциты дата [ТПП, 100 дн]") %>%
  rename(Neutrophil_recovery = "Восстановление Нейтрофилы дата [ТПП,100 дн]") %>%
  rename(Platelet_recovery = "Восстановление Тр20 дата [ТПП, 100 дн]") %>%
  rename(Rejection_date = "Дата отторжения [ТПП,100дн]") %>%
  rename(Patient_ID = "Рег номер пациента") %>%
  rename(TKM_number = "Порядковый номер настоящей трансплантации[ПТКМ,ПДИТКМ]")  %>%
  
  # фильтрация  - убираем лишние строки сразу
  filter(Reconstitution != "death_before" ) %>%
  filter(Diagnosis == "Acute_leukemia" ) %>%
  filter((Source_sc != "cord_blood")) %>%
  filter(TKM_number == 1) %>%

  # Изменение содержимого стобцов
  # BMI
  mutate(BMI = as.numeric(gsub(",", ".", BMI) )) %>%    # заменить точки на запятые
  mutate(BMI = ifelse( (BMI > 100), BMI/10, BMI)) %>%   # исправляем ошибку в данных BMI
  mutate(BMI = ifelse((BMI == 0.0), NA, BMI)) %>%       # 0 в NA
  
  # Reconstitution
  mutate(Reconstitution = factor(ifelse( (Reconstitution == "no"), "no", "yes"))) %>%
  
  # BMT_kind
  mutate(BMT_kind = case_when(
    grepl ("аллогенная_неродственная", BMT_kind) ~ "allogeneic_unrelated",
    grepl ("аллогенная_родственная", BMT_kind) ~ "allogeneic_related",
    grepl ("гаплоидентичная", BMT_kind) ~ "haploidentical"))  %>%
  
  # Restage_on_TKM_point перевод и замена: ремиссия и рецидив,остальные - unknown
  mutate(Restage_on_TKM_point = case_when(
    grepl ("ремиссия", Restage_on_TKM_point) ~ "remission",
    grepl ("рецидив", Restage_on_TKM_point) ~ "relapse",
    TRUE ~ "unknown"))   %>%
  
  # Sex перевод
  mutate(Sex = case_when(
    grepl ("Мужской", Sex) ~ "male",
    grepl ("Женский", Sex) ~ "female")) %>%
  
  # Объединяем виды Source_sc
  mutate(Source_sc = case_when(
    grepl ("BM", Source_sc) ~ "BM",
    grepl ("PBSC", Source_sc) ~ "PBSC")) %>%

  # Новая колонка - комбинаци BMT_kind & HLA_match
  mutate(Transplantation_groups = case_when( 
    (BMT_kind ==  "allogeneic_related") ~ "allogeneic_related", 
    (BMT_kind ==  "haploidentical") ~ "haploidentical",  
    ( (BMT_kind ==  "allogeneic_unrelated") & (HLA_match ==  "matched")) ~  
      "allogeneic_unrelated_matched", 
    ( (BMT_kind ==  "allogeneic_unrelated") & (HLA_match ==  "mismatched")) ~  
      "allogeneic_unrelated_mismatched"  ))  %>%
  
  
  #Отбираем нужные переменных
  select(c(Patient_ID, Donor_sex,  Disease_state_reconstitution,  #Diagnosis
           HLA_match, BMT_kind,
            Restage_on_TKM_point, Age, BMI, Conditioning, 
            Source_sc, Reconstitution, Sex, Transplantation_groups))
            
```

## Смотрим преобразованные данные

```{r }

View(df)
str(df)
```


```{r }
# Collect Patien_IDs
write.table(df$Patient_ID, file='Проект гемопоез, отобранные пациенты.tsv', row.names = FALSE, col.names = FALSE)

```

## В переменной Transplantation_groups - основное отличие между Reconstitution yes/no
Transplantation_groups 
```{r }
# Данные
table(df$Transplantation_groups)
prop.table(table(df$BMT_kind, df$HLA_match))

```
Таблицы сопряженности

```{r }

#Таблицы сопряженности
prop.table(table(df$Reconstitution, df$Transplantation_groups))
#table(df$Reconstitution, df$Transplantation_groups)

```


Тесты

```{r }

# Тесты
chisq.test(df$Reconstitution, df$Transplantation_groups)
fisher.test(df$Reconstitution, df$Transplantation_groups)
```

График

```{r }

# График    
ggplot(df, aes(x =  Reconstitution,
               fill = Transplantation_groups )) +
  geom_bar(position = "fill") +
  theme_classic()

```

#Еще одна переменная, по которой есть значимое отличие - Source_sc

```{r }

table(df$Source_sc)
# тут есть  редкие значения BM+BM = 1, BM+PBSC = 1, cord_blood =1, PBSC+PBSC=1
# их дропнуть, преобразовать или так оставить


```

```{r }

#Таблицы сопряженности
prop.table(table(df$Reconstitution, df$Source_sc))
table(df$Reconstitution, df$Source_sc)

# Тесты
chisq.test(df$Reconstitution, df$Source_sc)
fisher.test(df$Reconstitution, df$Source_sc)

# График    
ggplot(df, aes(x =  Reconstitution,
               fill = Source_sc)) +
  geom_bar(position = "fill") +
  theme_classic()


```
# Другие графики 
```{r }

hist(df$Age)
hist(df$BMI)


```
# Другие графики 
```{r }
p1 <- ggplot(df, aes(x = Reconstitution, y = BMI,
                    fill = Reconstitution)) +
  geom_boxplot() +
  geom_jitter()
p1 + scale_fill_brewer(palette = "YlGn") + theme_classic() + stat_compare_means()

#######################################
p2 <- ggplot(df, aes(x = Reconstitution, y = Age,
                    fill = Reconstitution)) +
  geom_boxplot() +
  geom_jitter()
p2 + scale_fill_brewer(palette = "GnBu") + theme_classic() + stat_compare_means()

#######################################
p3 <- ggplot(df, aes(x =  Reconstitution, y = BMI)) +
  geom_violin(fill = "yellow",
              alpha = 0.5,
              width = 0.6) +
  geom_boxplot(fill = "lightgreen",
               width = 0.3)
p3 + scale_fill_brewer(palette = "YlGn") + theme_classic() + stat_compare_means()
  

######################################
p4 <- ggplot(df, aes(x = Reconstitution,
               fill = Donor_sex)) +
  geom_bar()
p4 + scale_fill_brewer(palette = "GnBu") + theme_classic()


######################################
p5 <- ggplot(df, aes(x = Reconstitution,
               fill = Sex)) +
  geom_bar()
p5 + scale_fill_brewer(palette = "GnBu") + theme_classic()

######################################
p6 <- ggplot(df, aes(x =  Reconstitution,
               fill = Sex)) +
  geom_bar(position = "fill")
p6 + scale_fill_brewer(palette = "GnBu") + theme_classic()

# посчитать тест на значимость различий

######################################
p7 <- ggplot(df, aes(x =  Reconstitution,
               fill = Restage_on_TKM_point)) +
      geom_bar(position = "fill")
p7 + scale_fill_brewer(palette = "YlGn") + theme_classic()

# посчитать тест на значимость различий

######################################
p8 <- ggplot(df, aes(x =  Reconstitution,
               fill = HLA_match)) +
  geom_bar(position = "fill") 
p8 + scale_fill_brewer(palette = "Paired") + theme_classic()

######################################
p9 <- ggplot(df, aes(x =  Reconstitution,
               fill = Disease_state_reconstitution)) +
  geom_bar(position = "fill")
p9 + scale_fill_brewer(palette = "Paired") + theme_classic()


######################################
p10 <- ggplot(df, aes(x =  Reconstitution,
               fill = Conditioning)) +
  geom_bar(position = "fill")
p10 + scale_fill_brewer(palette = "YlGn") + theme_classic()


```

```{r }
#########################################################################
# Test and train
set.seed(42)
default_idx = sample(nrow(df), 500)
default_trn = df[default_idx, ]
default_tst = df[-default_idx, ]

table(default_trn$Reconstitution)
table(default_tst$Reconstitution)

##################################################################

```

```{r }
#########################################################################
# Regression
# https://www.datacamp.com/community/tutorials/logistic-regression-R
# Строим модель
glm.fit <- glm(Reconstitution ~ Transplantation_groups + Source_sc + Age, 
               data = default_trn, family = binomial)

# смотрим на модель
summary(glm.fit)

coef(glm.fit)

head(predict(glm.fit))

glm.probs <- predict(glm.fit, type = "response")
glm.probs[1:10]

# Как она предсказывает на трейне, порог тут 0,9 - можно менять
glm.pred <- ifelse(glm.probs > 0.9, "yes", "no")
attach(default_trn)
table(glm.pred, Reconstitution)
#table(glm.pred, default_trn$Reconstitution)

##################################################################

```

```{r }
#########################################################################
# Строим ROC/AUC на тестовой выборке
library(pROC)
test_prob = predict(glm.fit, newdata = default_tst, type = "response")
test_roc = roc(default_tst$Reconstitution ~ test_prob, plot = TRUE, print.auc = TRUE)

##################################################################

```
